spring:
  session:
    storage-type: redis
  redis:
    host: localhost
    port: 6379
  #  임시계정과 임시 비밀번호
  security:
    user:
      name: user
      password: PasswordEncored.password(password)
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/board
    username: root
    password: 1234
  jpa:
    show-sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MariaDBDialect
    generate-ddl: true
    properties:
      hibernate:
        ddl-auto: validate
        format_sql: true
        show_sql: true
    hibernate:
      ddl-auto: update

#    실행시 마다 밑에 sql문이 보이게 하기

logging:
#  로그파일 경로와 파일명 지정
  file:
    name: logs/app.log
  level:
#    trace < debug < info < error 순서의 로그래벨을 가짐
#    info로 설정시 trace, debug로그는 출력되지 않음
    root: info


