#port?? ???!!!!
#application.prrperties? ?? - yml? ????? ???

#server.port=8081

#DB??#
#spring.datasource.url=jdbc:mariadb://localhost:3306/member
#spring.datasource.username=jdbc"mariadb://localhost:3306/root
#spring.datasource.userpassword=jdbc"mariadb://localhost:3306/1234



#yml??? port?? ??, ????? ????? ????., "=" ?? ":"? ????
#sever:
#  port: 8081

#DB??#
#spring:
#  profile:
#    active:dev
# or  profile:
##    active:prod
#  datasource:
#    url: jdbc:mariadb://localhost:3306/member
#    username: root
#    password: 1234
# ---
#sever:
#  port: 8082
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/basic
    username: root
    password: 1234
  jpa:
    database: mysql
    #    innoDB ???? ??
    database-platform: org.hibernate.dialect.MariaDBDialect
    #   ???? ?? ?? ??
    generate-ddl: true
    hibernate: #jpa? ???
      #      create??? ?? table? drop? ??
      #      update??? ????? alter? ??
      #      validate? ??DB?? ???? check
      #      ????? update ?? validate??
      ddl-auto: update
    #     ddl-auto: validate ???? ???? ???, ???? ??? ??. create? ?? ??, update? ?? ??? ??? ???.
    #    creat: ?? DDL? ???? ??(????, ?? ?? ?)
    #    update: ?? ?? ?? X, ?? ?? ?? -> raw ddl ??? DB??
    #    validate: DB?? ??X ->???? return??
    #      jpa? ???? ??? ????, ??? console?? ?????
    show_sql: true
#   show_sql console?? ????

#?? ??? ??? ????
mybatis:
  mapper-locations: classpath:/mapper/**/*.xml
